### ISSUE TITLE
Redundant testing data.

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/run_brer#16]
The `pair_data.json` file is redundant with the `raw_pair_data` test fixture. One should be derived from the other (or removed).

Note that the `run_brer/data` was removed at some point in the git history of this repo or the `sample_restraint` because the sample input file could be obtained elsewhere, but we need to continue to include it for the moment in order to support all gmxapi releases.

**Comment by eirrgang** [comment]
My main concern was the duplication of `pair_data` in this repo. It would be nice to get rid of the stashed `topol.tpr`, but I think that's a separate issue, and probably much further down the road.

**Comment by carolinedav** [comment]
Looks good to me!
