### ISSUE TITLE
Interrupted simulations cause premature phase advancement

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/run_brer#19]
GROMACS simulations exit without error when terminating early due to the run time `max_hours` parameter or even a job time-out.

`run_brer` allows the BRER "phase" or "iteration" to advance when the simulation exits without crashing the script. Instead, `RunConfig.run()` should do some checking before advancing the BRER state.

## Convergence phase

For the convergence phase, we use the `linearstop_restraint` plugin. This code [stores and uses a value](https://github.com/kassonlab/brer_plugin/blob/dc91b0b03ee302d28ff9494145cf82f7081142e2/src/cpp/linearstoppotential.h#L80) associated with convergence, but doesn't currently export it.

We can add another accessor (like [`getTime()`](https://github.com/kassonlab/brer_plugin/blob/dc91b0b03ee302d28ff9494145cf82f7081142e2/src/cpp/linearstoppotential.h#L60))  to the plugin and [bind a new output property](https://github.com/kassonlab/brer_plugin/blob/dc91b0b03ee302d28ff9494145cf82f7081142e2/src/pythonmodule/export_plugin.cpp#L651).

Then, the convergence phase can read values from the plugin the same way the training phase does (e.g. [alpha](https://github.com/kassonlab/run_brer/blob/532e5edf177734733a11c511e75cde922fccaf5a/run_brer/run_config.py#L369) and [target](https://github.com/kassonlab/run_brer/blob/532e5edf177734733a11c511e75cde922fccaf5a/run_brer/run_config.py#L371))

Then, we will use this information before [updating the state](https://github.com/kassonlab/run_brer/blob/532e5edf177734733a11c511e75cde922fccaf5a/run_brer/run_config.py#L514).

Given that the gmxapi context is returned by the functions that perform each phase of work, we might choose to inspect the plugin output in `rc.run()` or in a new `check...` function called by `rc.run()` rather than in the `__convergence` function, since it is (at least currently) the responsibility of `rc.run()` to advance the phase.

## Production phase

To check whether we have generated a trajectory of the prescribed length, we can add a `time` attribute to an additional potential, and compare its value to that obtained at the end of the convergence phase.

## Also

Note that, for correctness and future-proofing, we should check whether we are in an MPI context and reduce the values from other plugins, but that might not apply to the current run_brer version, and isn't necessary for initial steps at a solution. (See #18)

Similar to #8

**Comment by carolinedav** [comment]
I think one way of doing it is implementing an if statement as a check-in? It might be tendinous to check every log file, but I'm not sure what other files would give us distance vs. target distance 
```elif phase == 'convergence':
            context = self.__converge(tpr_file=tpr_file, **kwargs)
            self.run_data.set(phase='production')```
            
to 

```elif phase == 'convergence':
            context = self.__converge(tpr_file=tpr_file, **kwargs)
            for log in log_file:
               log.readline(-1)
               if ...
            self.run_data.set(phase='production')```

**Comment by carolinedav** [comment]
Updates to resolve issue #19: 
1. Utilize [stop_not_called](https://github.com/kassonlab/brer_plugin/blob/dc91b0b03ee302d28ff9494145cf82f7081142e2/src/cpp/linearstoppotential.h#L80) to check convergence state before production. 

2. Define variable to [linearStop.def_property_readonly](https://github.com/kassonlab/brer_plugin/blob/dc91b0b03ee302d28ff9494145cf82f7081142e2/src/pythonmodule/export_plugin.cpp#L651) as: 
```c++
  linearStop.def_property_readonly("stop_not_called", [](PyLinearStop *potential) {
    return static_cast<plugin::LinearStopRestraint *>(potential->getRestraint().get())
        ->getStop();
  });
```
above
```c++
  linearStop.def_property_readonly("time", [](PyLinearStop *potential) {
    return static_cast<plugin::LinearStopRestraint *>(potential->getRestraint().get())
        ->getTime();
  });

  m.def("linearstop_restraint", [](const py::object element) {
    return createLinearStopBuilder(element);
```

3. Define `getStop()` like [`getTime()`](https://github.com/kassonlab/brer_plugin/blob/dc91b0b03ee302d28ff9494145cf82f7081142e2/src/cpp/linearstoppotential.h#L60) as:
```c++
bool getStop() { return stop_not_called_; }
```
4. Allow convergence to read `stop_not_called` along with [alpha](https://github.com/kassonlab/run_brer/blob/532e5edf177734733a11c511e75cde922fccaf5a/run_brer/run_config.py#L369) and [target](https://github.com/kassonlab/run_brer/blob/532e5edf177734733a11c511e75cde922fccaf5a/run_brer/run_config.py#L371) as: 
```python
current_stop_not_called = context.potentials[i].stop_not_called
``` 
and to be continued...

**Comment by eirrgang** [comment]
We want the phase to be incomplete until "stop" has been called.

As a side note, code style guides tend to point out that it is least brain-twisting to adopt a convention of affirmatively named boolean variables. It might be a good idea for an initial commit to swap the logic and rename `stop_not_called` to `stop_called`.

In any case, I think the value to export would be
```cpp
linearStop.def_property_readonly("stop_not_called", [](PyLinearStop *potential) {
    return static_cast<plugin::LinearStopRestraint *>(potential->getRestraint().get())
        ->getStopCalled();
  });
```

to fetch `!stop_not_called` (or `stop_called`).

Then, we should only update `self.run_data.set(phase='production')` if `all(potential.stop_called for potential in context.potentials)`.

Note: In case there are other potentials attached or an old version of `brer` is in use, we can avoid making it an error for the attribute to be missing:
```python
if all(getattr(potential, 'stop_called', True) for potential in context.potentials):
    self.run_data.set(phase='production')
```

**Comment by eirrgang** [comment]
Note: a similar problem can occur if the production phase simulation shuts down cleanly, but early. The simplest solution is to check whether the plugin has reached the target time/step. I'll follow up on this later in the week.

**Comment by eirrgang** [comment]
Updates for both https://github.com/kassonlab/run_brer and https://github.com/kassonlab/brer_plugin have been merged to their respective `master` branches.
