### ISSUE TITLE
Establish versioning and release policies

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/run_brer#25]
This issue concerns the `run_brer` project as well as the https://github.com/kassonlab/brer_plugin project.

We did not import a tag for the `run_brer` release associated with @jmhays 1.0 code when we moved the repository. I think I have a local repository somewhere that can identify the commit to which such a tag should refer, but it is also possible that there was not a tagged release for `run_brer` at all. If there was, it seems like it would be reasonable to duplicate the tag in the kassonlab/run_brer project. Otherwise, it seems reasonable to assign one.

The changes in https://github.com/kassonlab/run_brer/pull/20 aren't really API breaking, but they definitely warrant a version bump from the version at original publication time. I'm not sure what the version bump should be or whether we should tag a new release right away, but it is significant that the updated package looks for the `brer_plugin` module rather than the `myplugin` module.

`brer_plugin` has a [v1 branch](https://github.com/kassonlab/brer_plugin/tree/v1) corresponding to the `sample_restraint` fork that @jmhays published with. We could tag it for archival purposes, but we should definitely tag a superior release first to avoid confusion. There are few changes to the @jmhays code other than the Python module name. It may be simplest to skip `brer 1.0` and just tag the master branch with `v2.0.0` as the first release under the `brer` package name, since the git history of https://github.com/kassonlab/brer_plugin includes the `sample_restraint` and `myplugin` commits and since we would prefer not to confuse people by implying that the first tagged release of `brer` is identically the package described in DOI: [10.1021/acs.jpclett.9b01407](https://pubs.acs.org/doi/10.1021/acs.jpclett.9b01407)

## Important notes

* The plugin for DOI: [10.1021/acs.jpclett.9b01407](https://pubs.acs.org/doi/10.1021/acs.jpclett.9b01407) is from a particular branch of a fork of the `sample_restraint` project (currently available at https://github.com/kassonlab/brer_plugin/tree/v1). The Python package name `myplugin` was left unchanged from the sample code.
* The current kassonlab/run_brer `master` branch refers to the `myplugin` module, per the original @jmhays code.
* The current kassonlab/run_brer `devel` branch (slated for merge with #20 ) references the `brer` module for plugins. The `brer` module is available at the https://github.com/kassonlab/brer_plugin/ `master` branch.
* I have neglected to compile release notes for the updates since importing these projects to `kassonlab`.

## Questions

* Is there a tag name for the `sample_restraint` commit associated with [10.1021/acs.jpclett.9b01407](https://pubs.acs.org/doi/10.1021/acs.jpclett.9b01407)?
    * Answer: https://github.com/jmhays/sample_restraint/releases/tag/v1.0.0-BRER
* Is there a tag name for the `run_brer` package associated with [10.1021/acs.jpclett.9b01407](https://pubs.acs.org/doi/10.1021/acs.jpclett.9b01407)?
    * Answer: TBD, but `run_brer` uses versioneer.py configured to use `git` tags.
* Is it okay to tag the @jmhays versions of the packages as 1.0 and the @kassonlab versions as 2.0?
* Do we want to resolve more of the outstanding issues before
  * merging #20?
  * tagging a new `run_brer` release?
* What are our thoughts on change log / release notes?

## Proposals

* Tag the @jmhays versions of the packages as 1.0 and the @kassonlab versions as 2.0.
* Merge https://github.com/kassonlab/run_brer/pull/20 (once `brer_plugin` has a tagged release for the current `master` branch, but before tagging `run_brer` 2.0).
* Once
    - [ ] tags are in place
    - [ ] automated testing is updated,
  we can
  * Apply [semantic versioning policy](https://semver.org/)
  * Use Versioneer metadata maintenance
  * Publish releases to pypi.org

**Comment by peterkasson** [comment]
Proposal sounds good for me.  We don't to my knowledge have tags associated with the prior papers, but if we can identify the appropriate commits that would be helpful.  Since that's tagging, it can be done independently of version numbering.

**Comment by eirrgang** [comment]
> Proposal sounds good for me. We don't to my knowledge have tags associated with the prior papers, but if we can identify the appropriate commits that would be helpful. 

My recollection is that `run_brer` may have never been tagged, but I found https://github.com/jmhays/sample_restraint/releases/tag/v1.0.0-BRER which _does_ correspond to https://github.com/kassonlab/brer_plugin/tree/v1

> Since that's tagging, it can be done independently of version numbering.

@jmhays set up the `run_brer` package with version metadata managed by [versioneer](https://github.com/python-versioneer/python-versioneer), configured to get version info from `git` tags. However,
* it may not have been used yet, and
* you can tell `versioneer` what tag prefix pattern to use for identifying versioning points, so it is easy to apply tags that do not affect the behavior of versioneer.

**Comment by eirrgang** [comment]
Some brief updates:

* We are now using `versioningit` to maintain version metadata in terms of git tags. We use the pattern `v*` to associated tags of the form `vX.Y` with version `"X.Y"`.
* We have tagged a few "beta" versions in advance of a 2.0 release. Caroline and I are owners of the `run_brer` namespace on the primary and test servers for PyPI.
* I will add a small document about preparing and posting tagged releases, probably in conjunction with #61 .
* We plan to tag and release run_brer 2.0 sometime this fall.

**Comment by eirrgang** [comment]
BRER 2.0 will be released as a `brer-md` package that includes both the Python and C++ components. The repository is evolving at https://github.com/kassonlab/brer-md
