### ISSUE TITLE
Incorporate `brer_plugin` into `run_brer`.

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/run_brer#71]
I am strongly considering merging the `brer_plugin` repository into the `run_brer` repository. I don't see any particularly good reason to keep them separate, and it can be a pain to maintain both. Also, then `brer_plugin` would automatically be available on PyPI as part of `run_brer`. We might choose to rename the package to, simply, `brer`, (or perhaps `brer-md`?)

The main potential downside is that the brer_plugin is trickier to install than `run_brer` because of its C++ dependencies on GROMACS libraries. However,
* `run_brer` already depends on the `gmxapi` Python package, which similarly depends on a GROMACS installation.
* We don't currently have any use cases for `run_brer` that don't necessitate a `brer_plugin` installation, anyway. Overall, a single installation is arguably simpler and can benefit from environment inspection tools in `gmxapi`. (Again, the `gmxapi` package is a dependency of `run_brer`, but `brer_plugin` currently has only a primitive CMake level dependency on GROMACS libraries, for simplicity. But having `gmxapi` available when doing the `brer_plugin` install would be handy.)

Then again, we _might_ have use cases that don't involve `brer_plugin` if we incorporate more analysis features into `run_brer`. This, in turn, could be mitigated by putting the analysis features into a separate package that is even lighter-weight than the current run_brer. Maybe `brer-tools`? This is a somewhat hypothetical point, though, and doesn't necessarily need to be resolved at the same time.

## Notes on legacy version support

I believe that `run_brer`, `brer_plugin`, and the `brer-md` works in progress all support GROMACS 2019 and gmxapi 0.0.7 through GROMACS 2023 and gmxapi 0.0.4. We need to make sure this is tested, though, and if there are installation caveats, those need to be documented.

We also need to revitalize our Singularity (and Docker?) recipes.

For users of gmxapi 0.0.7, it may be appropriate to provide a 0.0.7 sdist on https://pypi.org/project/gmxapi/.

In any case, we need to make sure the instructions are clear for GROMACS versions back through 2019 and gmxapi versions back through 0.0.7.

### Example case

At one external site, the sysadmins make BRER available to users through Singularity with the following scriptlet in their image builder.

    git clone --depth=1 -b release-0_0_7 https://github.com/kassonlab/gmxapi.git
    cd gmxapi
    mkdir build; cd build
    cmake ../ -Dgmxapi_DIR=/usr/local/gromacs/share/cmake/gmxapi -DGMXAPI_INSTALL_PATH=/usr/local/lib/python3.6/dist-packages/gmx
    make -j8 install

### Avoiding version mismatch problems

Modern Python package build front-ends use an isolated build environment by default. This isolated environment may or may not have access to the parent environment's *system-site-packages*. This could cause confusion for users who intend to use an older version of gmxapi that is not binary compatible with the latest version.

It may be appropriate to advise people who want less-than-the-latest versions of dependencies to install dependencies first and use `--no-build-isolation` and/or `--no-deps` when installing `brer-md`. Otherwise, it is conceivable that someone may end up with the `brer.md` C++ extension built for the latest gmxapi in the automatically-generated ephemeral build environment, but then the package may be installed in an environment with older, possibly binary-incompatible packages. (We are trying to keep `gmxapi` ABI compatible for 0.0.3.1+, but previous versions are definitely not binary compatible.)

To reduce surprising errors, we should probably customize the [metadata that is generated](https://peps.python.org/pep-0517/#prepare-metadata-for-build-wheel) for the built package (the *wheel*) to require exactly the gmxapi version for which it was built. We are only distributing `sdist` packages on pypi.org, since the *wheel* depends on too many details about the local gromacs installation. Since the *wheel* will not be portable outside of its intended installation environment, it can have stronger site-specific dependencies that would not be suitable for an archive on a public package index. We will need to document what users will encounter if they attempt to install the locally built *wheel* in an environment with a different gmxapi installation, and what their options are.

We also need to consider (and document) what the user will experience and how to upgrade the brer-md dependent when the gmxapi (dependency) package is upgraded to an ABI incompatible version. (Our advice still can and should be "Use a fresh venv for each research project and keep a consistent tool kit in the interest of scientific reproducibility," but we don't have to be pushy.)

**Comment by peterkasson** [comment]
I think there's a decent case to merge. If someone wanted an alternate to
brer_plugin, they'd still need to install something, so the install
complexity would still be there?

Best,
Peter

**Comment by eirrgang** [comment]
I believe this is mostly resolved, now, with the new https://github.com/kassonlab/brer-md/ repository. I will try to enumerate remaining tasks as new issues at the new repository, and then close this issue.
