### ISSUE TITLE
Training phase may not be robust to simulation failure.

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/run_brer#8]
It may be that failed simulations during the training phase do not prevent the run_brer state from advancing.

This would allow the convergence phase to begin with alpha values that aren't trained, such as the initial value of zero. (This is a pathological case that has appeared in practice, but we aren't completely sure of the cause yet.)

**Comment by eirrgang** [comment]
Confirmed.

**Comment by eirrgang** [comment]
It looks like this also requires changes to the gmxapi package. (Note the unsatisfactory resolutions to https://github.com/kassonlab/gmxapi/issues/121 and https://github.com/kassonlab/gmxapi/issues/125)

Unfortunately, this issue is also somewhat tied to problematic libgromacs behavior. gmx::Mdrunner::mdrunner() does not always return non-zero in conditions that we would want to consider "failures," and behavior can be inconsistent across GROMACS releases. We might not be able to resolve this for gmxapi 0.0.7+GROMACS2019.

**Comment by carolinedav** [comment]
How simple would it be to include an if statement in the training phase like: 
`if current_alpha == 0.0:
	raise RuntimeError('Alpha values were constrained to 0.0')`

**Comment by eirrgang** [comment]
> How simple would it be to include an if statement in the training phase like:
> `if current_alpha == 0.0: raise RuntimeError('Alpha values were constrained to 0.0')`

I believe we should do so, both in run_brer and in the brer_plugin. See also https://github.com/kassonlab/brer_plugin/issues/3

**Comment by eirrgang** [comment]
We should forget about checking the status of the simulation itself, for now. We can resolve this similarly to how we dealt with the convergence and production phases.

**Comment by carolinedav** [comment]
By using `stop_called` in training?

**Comment by eirrgang** [comment]
> By using `stop_called` in training?

I think there is actually a `is_converged` data member, but it may not be exported to Python yet. Recall that each of the phases uses a different potential: https://kassonlab.github.io/run_brer/developer_api.html#run_brer.plugin_configs.TrainingPluginConfig

**Comment by carolinedav** [comment]
Solution to #8:
1. In `brer_plugin`, utilize private `bool converged{0}` in 'brerpotential.h' with 'bool getConverged() { return converged_;}`
Note: Should we add `using BRER::getConverged;` in `brerpotential.h` as well?
2. Instantiate `current_converged` by `context.potentials[i].converged` in `run_config.py` and set by `self.run_data.set(name=current_converged, converged=current_converged)`  in training
Note: Should we log this information with `_logger.info`? I would assume so for continuity.
3. Check for `converged` in `def run` with
```python
        if phase == 'training':
            context = self.__train(tpr_file=tpr_file, **kwargs)
            if all(getattr(potential, 'converged', True) for potential in context.potentials):
                self.run_data.set(phase='convergence')
            else:
                self._logger.warning(
                    '')
```

Clarifying question: Since training sets up the alpha value and the issue is when alpha = 0.0, how is `converged` used in training?

**Comment by eirrgang** [comment]
> 1. In `brer_plugin`, utilize private `bool converged{0}` in 'brerpotential.h' with 'bool getConverged() { return converged_;}`
Make sure the variable names is consistent w.r.t. the trailing underscore, but yes. :-)

> Note: Should we add`using BRER::getConverged;`in`brerpotential.h` as well?

The Python bindings are for the `BRERRestraint` class, which inherits privately from the `BRER` class. So in order to access `BRER::getConverged` as `BRERRestraint::getConverged`, `BRERRestraint` needs a `using BRER::getConverged` in its `public` section.

> 2. Instantiate `current_converged` by `context.potentials[i].converged` in `run_config.py`

Yes. (But it's a good idea to have a safe-guard in case the attribute isn't present, as we do in the other examples that get a default value or simply don't get included in the list comprehension).

> and set by `self.run_data.set(name=current_converged, converged=current_converged)`  in training

I don't think we need to add `converged` to the `required_parameters` and to set it in the state file. For one thing, I don't think we are able to reinitialize a partially-complete training phase, so we will never be restoring the `converged` state or initializing the plugin with a non-default value.

>    Note: Should we log this information with `_logger.info`? I would assume so for continuity.

Sounds good.

> 3. Check for `converged` in `def run` with
> 
> ```python
>         if phase == 'training':
>             context = self.__train(tpr_file=tpr_file, **kwargs)
>             if all(getattr(potential, 'converged', True) for potential in context.potentials):
>                 self.run_data.set(phase='convergence')
>             else:
>                 self._logger.warning(
>                     '')
> ```

Looks good to me.

> Clarifying question: Since training sets up the alpha value and the issue is when alpha = 0.0, how is `converged` used in training?

Well, yes, we should also be checking the value of alpha. One of the reasons that we can end up with a zero value for alpha is that the training phase could erroneously advance while alpha is still 0. Or it could erroneously advance before alpha has truly converged. However, it is plausible that alpha could be zero _and_ the training phase could appear converged because it is accidentally initialized in the target configuration.

I'm not sure how best to handle this. It seems like options could include
* producing an error that training alpha for the current target value was not possible with the provided initial conformation
* somehow automatically choosing either a different initial conformation or a different target
* choosing some default non-zero value of alpha

For the moment, I don't know how to do better than just producing and error and refusing to proceed into the convergence phase with an alpha value of zero. But that would be a check to add to the convergence phase. Maybe @peterkasson has thoughts on something we might do in the training phase, but it seems likely that manual human intervention would be needed if we randomly choose a target value that is so close to the input conformation that convergence is prematurely detected.

**Comment by eirrgang** [comment]
> I would note, though, that this is beyond the scope of "Training phase may not be robust to simulation failure" and needn't be resolved in the present issue. Just checking the convergence value is a nice well-compartmentalized bug-fix here.

See https://github.com/kassonlab/brer_plugin/issues/3 for an alternative place to document problems and solutions relating to an alpha value of 0 being propagated due to prematurely detected convergence.

**Comment by eirrgang** [comment]
> 1. with 'bool getConverged()

Also, don't forget something like
```cpp
  brer.def_property_readonly("converged", [](PyBRER *potential) {
    return static_cast<plugin::BRERRestraint *>(potential->getRestraint().get())
        ->getConverged();
  });
```

in the `export_plugin.cpp`

**Comment by carolinedav** [comment]
Updated `export_plugin.cpp`!

**Comment by eirrgang** [comment]
> Updated `export_plugin.cpp`!

Do you have a branch or fork of https://github.com/kassonlab/brer_plugin for a pull request?

I think this is separate from https://github.com/kassonlab/brer_plugin/issues/3, right?

**Comment by carolinedav** [comment]
I was working off of the `cnd7cy` branch but I can make a new branch labelled as `rb8` or likewise!

**Comment by eirrgang** [comment]
> I was working off of the `cnd7cy` branch but I can make a new branch labelled as `rb8` or likewise!

It is helpful if the branch name is descriptive of its purpose. I like to include the issue number. I used "rb" to stand for "run_brer" (the name of the repository), so it wouldn't normally be an appropriate prefix for the brer_plugin repo. But a prefix is not necessary.

I've created a new issue in an attempt to reduce confusion and keep the conversation focused on patches for the two respective repositories. https://github.com/kassonlab/brer_plugin/issues/16

I don't think you will have any trouble issuing a pull request from your personal fork, but I believe you have permission to create new branches directly in kassonlab/brer_plugin, which might be easier.

You can name the branch whatever you want.

**Comment by carolinedav** [comment]
LOL I totally thought `rb` was rebase my bad! I'll create a new branch in the kassonlab for `bp16`
